language: php
php:
- 5.6
- 7.0
- 7.1
env:
- WP_VERSION=4.9
- WP_VERSION=latest
before_script:
- composer global require phpunit/phpunit
- composer global require wp-coding-standards/wpcs
- phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
- bash bin/install-wp-tests.sh $WP_VERSION
script:
- phpcs
- phpunit
